coding style

diff --git a/dotfiles/bashrc b/dotfiles/bashrc
--- a/dotfiles/bashrc
+++ b/dotfiles/bashrc
@@ -3,9 +3,9 @@
 # see more in http://alias.sh/
 ######################################################################
 if [ -f ~/.git-completion.sh ]; then
-    source ~/.git-completion.sh
+  source ~/.git-completion.sh
 fi
-unalias ls > /dev/null 2>&1
+unalias ls >/dev/null 2>&1
 alias df="df -h"
 alias ls="ls -F"
 alias ll="ls -l"
@@ -27,127 +27,122 @@ alias gc='git commit'
 alias gad='git add'
 alias gst='git status -s'
 alias gdf='git df'
-if [ `uname` = "Darwin" ]; then
-    alias mp="open -a 'Media Player'"
-    alias subl="'/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl'"
-    alias lsusb="system_profiler SPUSBDataType"
-    alias code='/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code'
+if [ $(uname) = "Darwin" ]; then
+  alias mp="open -a 'Media Player'"
+  alias subl="'/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl'"
+  alias lsusb="system_profiler SPUSBDataType"
+  alias code='/Applications/Visual\ Studio\ Code.app/Contents/Resources/app/bin/code'
 fi
 
 ###################################
 ## build tags for cscope and ctag
 ###################################
-btags()
-{
-    find $PWD -name "*.h" -o -name "*.c" -o -name "*.cpp" -o -name "*.cc" -o -name "*.java" >cscope.files
-    ctags -L ./cscope.files
-    cscope -b
+btags() {
+  find $PWD -name "*.h" -o -name "*.c" -o -name "*.cpp" -o -name "*.cc" -o -name "*.java" >cscope.files
+  ctags -L ./cscope.files
+  cscope -b
 }
-cltags()
-{
-    rm -f cscope.files tags cscope.out
+cltags() {
+  rm -f cscope.files tags cscope.out
 }
 
 ###################################
 ## set terminal name
 ###################################
 tn() {
-    local name="Terminal"
-    if [[ $# -ne 0 ]]; then
-        name=$1
-    fi
-    echo -en "\033]0;$name\a"
+  local name="Terminal"
+  if [[ $# -ne 0 ]]; then
+    name=$1
+  fi
+  echo -en "\033]0;$name\a"
 }
 
 ###################################
 ## tmux
 ###################################
 tm() {
-    local created=0
-    if [[ $# -eq 0 ]]; then
-        tmux ls
-        return
+  local created=0
+  if [[ $# -eq 0 ]]; then
+    tmux ls
+    return
+  fi
+  if [[ $# -eq 1 ]]; then
+    tmux at -t $1
+    return
+  fi
+  sname=$1
+  OLDIFS=$IFS
+  IFS=','
+  for one in $2; do
+    [ -z $one ] && continue
+    if [ $created -eq 0 ]; then
+      tmux new -s $sname -n $one -d
+      created=1
+    else
+      tmux new-window -n $one -t $sname
     fi
-    if [[ $# -eq 1 ]]; then
-        tmux at -t $1
-        return
-    fi
-    sname=$1
-    OLDIFS=$IFS
-    IFS=','
-    for one in $2
-    do
-        [ -z $one ] && continue
-        if [ $created -eq 0 ]; then
-            tmux new -s $sname -n $one -d
-            created=1
-        else
-            tmux new-window -n $one -t $sname
-        fi
-    done
-    tmux at -t $sname
-    IFS=$OLDIFS
+  done
+  tmux at -t $sname
+  IFS=$OLDIFS
 }
 
 uts() {
-    if [[ $# -eq 0 ]]; then
-        date +%s
-    else
-        date +'%Y-%m-%d %H:%M:%S' -d @$1
-    fi
+  if [[ $# -eq 0 ]]; then
+    date +%s
+  else
+    date +'%Y-%m-%d %H:%M:%S' -d @$1
+  fi
 }
 uts.ms() {
-    if [[ $# -eq 0 ]]; then
-        date +%s%N|cut -c -13
-    else
-        local seconds=$(echo $1|cut -c -10)
-        local date_str="$(date +'%Y-%m-%d %H:%M:%S' -d @$seconds).$(echo $1|cut -c 11-)"
-        echo $date_str
-    fi
+  if [[ $# -eq 0 ]]; then
+    date +%s%N | cut -c -13
+  else
+    local seconds=$(echo $1 | cut -c -10)
+    local date_str="$(date +'%Y-%m-%d %H:%M:%S' -d @$seconds).$(echo $1 | cut -c 11-)"
+    echo $date_str
+  fi
 }
 uts.ns() {
-    if [[ $# -eq 0 ]]; then
-        date +%s%N
-    else
-        local seconds=$(echo $1|cut -c -10)
-        local date_str="$(date +'%Y-%m-%d %H:%M:%S' -d @$seconds).$(echo $1|cut -c 11-)"
-        echo $date_str
-    fi
+  if [[ $# -eq 0 ]]; then
+    date +%s%N
+  else
+    local seconds=$(echo $1 | cut -c -10)
+    local date_str="$(date +'%Y-%m-%d %H:%M:%S' -d @$seconds).$(echo $1 | cut -c 11-)"
+    echo $date_str
+  fi
 }
 
 ###################################
 ## clone github project
 ###################################
-hub()
-{
-    if [[ $# -eq 0 ]]; then
-        cd $HOME/usr/project/github
-        return 0;
-    fi
-    echo "==>start clone $1..." &&
-        git clone ssh://git@github.com/oswystan/$1 &&
-        cd $1 &&
-        git config --local user.name "oswystan" &&
-        git config --local user.email "oswystan@126.com" &&
-        cd - &&
+hub() {
+  if [[ $# -eq 0 ]]; then
+    cd $HOME/usr/project/github
+    return 0
+  fi
+  echo "==>start clone $1..." &&
+    git clone ssh://git@github.com/oswystan/$1 &&
+    cd $1 &&
+    git config --local user.name "oswystan" &&
+    git config --local user.email "oswystan@126.com" &&
+    cd - &&
     echo "==>succ" || echo "==>fail!!"
 }
 
 ###################################
 ## clone gitlab project
 ###################################
-lab()
-{
-    if [[ $# -eq 0 ]]; then
-        cd $HOME/usr/project/gitlab
-        return 0;
-    fi
-    echo "==>start clone $1..." &&
-        git clone git@gitlab.com:oswystan/$1.git &&
-        cd $1 &&
-        git config --local user.name "oswystan" &&
-        git config --local user.email "oswystan@126.com" &&
-        cd - &&
+lab() {
+  if [[ $# -eq 0 ]]; then
+    cd $HOME/usr/project/gitlab
+    return 0
+  fi
+  echo "==>start clone $1..." &&
+    git clone git@gitlab.com:oswystan/$1.git &&
+    cd $1 &&
+    git config --local user.name "oswystan" &&
+    git config --local user.email "oswystan@126.com" &&
+    cd - &&
     echo "==>succ" || echo "==>failed!!"
 }
 
@@ -155,17 +150,17 @@ lab()
 ## docker shortcuts
 ###################################
 dstart() {
-    echo "docker run -it --name wrtc -P ubuntu:16.04 /bin/bash"
+  echo "docker run -it --name wrtc -P ubuntu:16.04 /bin/bash"
 }
 denter() {
-    #docker run -it --name wrtc -P ubuntu:16.04 /bin/bash
-    _pid=`docker inspect -f {{.State.Pid}} $1`
-    HOME=/root LANG=en_US.UTF-8 LANGUAGE=en_US:en sudo nsenter --mount --uts --ipc --net --pid -w --target $_pid
+  #docker run -it --name wrtc -P ubuntu:16.04 /bin/bash
+  _pid=$(docker inspect -f {{.State.Pid}} $1)
+  HOME=/root LANG=en_US.UTF-8 LANGUAGE=en_US:en sudo nsenter --mount --uts --ipc --net --pid -w --target $_pid
 }
 _denter() {
-    cur="${COMP_WORDS[COMP_CWORD]}"
-    local opts=`docker ps --format '{{.Names}}'`
-    COMPREPLY=($(compgen -W "$opts" -- $cur))
+  cur="${COMP_WORDS[COMP_CWORD]}"
+  local opts=$(docker ps --format '{{.Names}}')
+  COMPREPLY=($(compgen -W "$opts" -- $cur))
 }
 complete -F _denter denter
 
@@ -173,142 +168,143 @@ complete -F _denter denter
 ## xz a directory
 ###################################
 z() {
-    if [ $# -ne 1 ]; then
-        echo "usage: z <file|directory>"
-        return 1
-    fi
-    tar Jcvf $1.tar.xz $1
+  if [ $# -ne 1 ]; then
+    echo "usage: z <file|directory>"
+    return 1
+  fi
+  tar Jcvf $1.tar.xz $1
 }
 
 ###################################
 ## extract files from a compressed file
 ###################################
 x() {
-    if [ $# -ne 1 ]; then
-        echo "usage: x <file>"
-        return 1
-    fi
-    if [ ! -f $1 ]; then
-        echo "ERROR: no such file [$1]"
-        return 1
-    fi
-    case $1 in
-        *.tar.bz2)
-            tar jxvf $1
-            ;;
-        *.tar.gz|*.tgz)
-            tar zxvf $1
-            ;;
-        *.tar.xz)
-            tar Jxvf $1
-            ;;
-        *.rar)
-            unrar x $1
-            ;;
-        *.zip)
-            unzip  $1
-            ;;
-        *)
-            echo "ERROR: unknown file format"
-    esac
+  if [ $# -ne 1 ]; then
+    echo "usage: x <file>"
+    return 1
+  fi
+  if [ ! -f $1 ]; then
+    echo "ERROR: no such file [$1]"
+    return 1
+  fi
+  case $1 in
+  *.tar.bz2)
+    tar jxvf $1
+    ;;
+  *.tar.gz | *.tgz)
+    tar zxvf $1
+    ;;
+  *.tar.xz)
+    tar Jxvf $1
+    ;;
+  *.rar)
+    unrar x $1
+    ;;
+  *.zip)
+    unzip $1
+    ;;
+  *)
+    echo "ERROR: unknown file format"
+    ;;
+  esac
 }
 
 ###################################
 ## top which the given name
 ###################################
 topg() {
-    top -c -p $(pgrep -d',' -f $1)
+  top -c -p $(pgrep -d',' -f $1)
 }
 
 ###################################
 ## check liveness of a service on a service
 ###################################
 live() {
-    if [[ $# -ne 2 ]]; then
-        echo "usage: live <server-ip> <port>"
-        return 1
-    fi
-    nc -z -w2 $1 $2 && echo "alive" || echo "dead"
+  if [[ $# -ne 2 ]]; then
+    echo "usage: live <server-ip> <port>"
+    return 1
+  fi
+  nc -z -w2 $1 $2 && echo "alive" || echo "dead"
 }
 
 k_linux() {
-    if [[ $# -eq 0 ]]; then
-        echo "Usage: k <only one target>"
-        return 1
-    fi
+  if [[ $# -eq 0 ]]; then
+    echo "Usage: k <only one target>"
+    return 1
+  fi
 
-    if [[ -d $1 ]]; then
-        (setsid nautilus "$1" >/dev/null 2>&1)
-        return 0;
-    fi
+  if [[ -d $1 ]]; then
+    (setsid nautilus "$1" >/dev/null 2>&1)
+    return 0
+  fi
 
-    case $1 in
-        *.md)
-            (setsid typora "$1" >/dev/null 2>&1)
-            ;;
-        *.js|*.html|*.txt|*.log|*.json|*.css|*.ts)
-            subl "$1" >/dev/null 2>&1
-            ;;
-        *.xls|*.xlsx|*.xlsm|*.csv)
-            (setsid et "$(pwd)/$1" >/dev/null 2>&1)
-            ;;
-        *.doc|*.docx)
-            (setsid wps "$(pwd)/$1" >/dev/null 2>&1)
-            ;;
-        *.ppt|*.pptx)
-            (setsid wpp "$(pwd)/$1" >/dev/null 2>&1)
-            ;;
-        *.bmp|*.png|*.jpeg|*.jpg)
-            (setsid eog "$1" >/dev/null 2>&1)
-            ;;
-        *.tar.bz2|*.tar.gz|*.tar.xz|*.tgz|*.zip)
-            (setsid file-roller "$1" >/dev/null 2>&1)
-            ;;
-        *)
-            vim $1
-            ;;
-    esac
+  case $1 in
+  *.md)
+    (setsid typora "$1" >/dev/null 2>&1)
+    ;;
+  *.js | *.html | *.txt | *.log | *.json | *.css | *.ts)
+    subl "$1" >/dev/null 2>&1
+    ;;
+  *.xls | *.xlsx | *.xlsm | *.csv)
+    (setsid et "$(pwd)/$1" >/dev/null 2>&1)
+    ;;
+  *.doc | *.docx)
+    (setsid wps "$(pwd)/$1" >/dev/null 2>&1)
+    ;;
+  *.ppt | *.pptx)
+    (setsid wpp "$(pwd)/$1" >/dev/null 2>&1)
+    ;;
+  *.bmp | *.png | *.jpeg | *.jpg)
+    (setsid eog "$1" >/dev/null 2>&1)
+    ;;
+  *.tar.bz2 | *.tar.gz | *.tar.xz | *.tgz | *.zip)
+    (setsid file-roller "$1" >/dev/null 2>&1)
+    ;;
+  *)
+    vim $1
+    ;;
+  esac
 }
 
 k_mac() {
-    if [[ $# -eq 0 ]]; then
-        echo "Usage: k <only one target>"
-        return 1
-    fi
+  if [[ $# -eq 0 ]]; then
+    echo "Usage: k <only one target>"
+    return 1
+  fi
 
-    if [[ -d $1 ]]; then
-        open "$1"
-        return 0;
-    fi
+  if [[ -d $1 ]]; then
+    open "$1"
+    return 0
+  fi
 
-    case $1 in
-        *.md)
-            open "$1"
-            ;;
-        *.js|*.html|*.txt|*.log|*.json|*.css|*.ts)
-            subl "$1" >/dev/null 2>&1
-            ;;
-        *.xls|*.xlsx|*.xlsm|*.csv)
-            open "$1"
-            ;;
-        *.doc|*.docx)
-            open "$1"
-            ;;
-        *.ppt|*.pptx)
-            open "$1"
-            ;;
-        *.bmp|*.png|*.jpeg|*.jpg)
-            open "$1"
-            ;;
-        *)
-            vim $1
-            ;;
-    esac
+  case $1 in
+  *.md)
+    open "$1"
+    ;;
+  *.js | *.html | *.txt | *.log | *.json | *.css | *.ts)
+    subl "$1" >/dev/null 2>&1
+    ;;
+  *.xls | *.xlsx | *.xlsm | *.csv)
+    open "$1"
+    ;;
+  *.doc | *.docx)
+    open "$1"
+    ;;
+  *.ppt | *.pptx)
+    open "$1"
+    ;;
+  *.bmp | *.png | *.jpeg | *.jpg)
+    open "$1"
+    ;;
+  *)
+    vim $1
+    ;;
+  esac
 }
 if [[ $(uname) = "Linux" ]]; then
-    alias k=k_linux
+  alias k=k_linux
 elif [[ $(uname) = "Darwin" ]]; then
-    alias k=k_mac
+  alias k=k_mac
 fi
 
 export BASH_SILENCE_DEPRECATION_WARNING=1
