add ttm hub.key ttm.key

diff --git a/dotfiles/zshrc b/dotfiles/zshrc
--- a/dotfiles/zshrc
+++ b/dotfiles/zshrc
@@ -16,6 +16,8 @@ export HOMEBREW_NO_AUTO_UPDATE=true
 export LC_ALL="en_US.UTF-8"
 
 ## alias
+alias vim=nvim
+alias vi=nvim
 alias cls="clear && printf '\033c'"
 alias ls=lsd
 alias ll="ls -l"
@@ -41,7 +43,9 @@ function vpn.on() {
 }
 
 function vpn.off() {
-  export https_proxy= http_proxy= all_proxy=
+  export https_proxy=
+  export http_proxy=
+  export all_proxy=
 }
 
 #################################
@@ -52,7 +56,7 @@ function z() {
     echo "usage: z <file|directory>"
     return 1
   fi
-  tar Jcvf $1.tar.xz $1
+  tar Jcvf "$1.tar.xz" "$1"
 }
 
 function x() {
@@ -60,25 +64,25 @@ function x() {
     echo "usage: x <file>"
     return 1
   fi
-  if [ ! -f $1 ]; then
+  if [ ! -f "$1" ]; then
     echo "ERROR: no such file [$1]"
     return 1
   fi
   case $1 in
   *.tar.bz2)
-    tar jxvf $1
+    tar jxvf "$1"
     ;;
   *.tar.gz | *.tgz)
-    tar zxvf $1
+    tar zxvf "$1"
     ;;
   *.tar.xz)
-    tar Jxvf $1
+    tar Jxvf "$1"
     ;;
   *.rar)
-    unrar x $1
+    unrar x "$1"
     ;;
   *.zip)
-    unzip $1
+    unzip "$1"
     ;;
   *)
     echo "ERROR: unknown file format"
@@ -91,14 +95,35 @@ function x() {
 ###################################
 hub() {
   if [[ $# -eq 0 ]]; then
-    cd $HOME/usr/project/github
+    cd "$HOME/usr/project/github"
     return 0
   fi
   echo "==>start clone $1..." &&
-    git clone git@github.com:oswystan/$1 &&
-    cd $1 &&
+    git clone "git@oswystan.github.com:oswystan/$1" &&
+    cd "$1" &&
     git config --local user.name "oswystan" &&
     git config --local user.email "oswystan@126.com" &&
     cd - &&
     echo "==>succ" || echo "==>fail!!"
+}
+
+hub.key() {
+  ssh-keygen -t ed25519 -C "oswystan@github" -f oswystan.github
+}
+
+ttm() {
+  if [[ $# -eq 0 ]]; then
+    cd "$HOME/usr/project/github"
+    return 0
+  fi
+  echo "==>start clone $1..." &&
+    git clone "git@ticktechman.github.com:ticktechman/$1" &&
+    cd "$1" &&
+    git config --local user.name "ticktechman" &&
+    git config --local user.email "geek.wystan@gmail.com" &&
+    cd - &&
+    echo "==>succ" || echo "==>fail!!"
+}
+ttm.key() {
+  ssh-keygen -t ed25519 -C "ticktechman@github" -f ticktechman.github
 }
